services:
  - type: web
    name: haveli-server
    runtime: node
    buildCommand: npm install && npm run db:generate && rm -rf apps/server/dist && npm run build --workspace=apps/server
    startCommand: npm run start --workspace=apps/server
    envVars:
      - key: NODE_ENV
        value: production
